### ISSUE TITLE
Slight issue in the "Simple Code" example 

### ISSUE THREAD

**Issue by waltergerych** [bes-dev/pytorch_clip_guided_loss#2]
I think there's a small error in the example you provided. You have

```
loss = loss_fn(image=var)["loss"]
```

I think this needs to be the following in order to run, though:

```
loss = loss_fn.image_loss(image=var)["loss"]
```

Also, thank you for this resource - this library will be very useful!

**Comment by bes-dev** [comment]
@waltergerych yes, thanks! Public API was changed, but we forget to change README too. We will fix it soon.

**Comment by bes-dev** [comment]
Done
